mutation uploadProductTranslations($locale: String!, $products: Upload!) {
  uploadProductTranslations(locale: $locale, products: $products)
    @context(provider: "vtex.admin-catalog-translation")
}
