query downloadSpecificationTranslations($requestId: String!) {
  downloadSpecificationTranslations(requestId: $requestId)
    @context(provider: "vtex.admin-catalog-translation") {
    fieldId
    name
  }
}
