query getAllCollections($locale: String!, $active: Boolean) {
  collectionTranslations(locale: $locale, active: $active)
    @context(provider: "vtex.admin-catalog-translation") {
    id
    name
    locale
    status
  }
}
