query GetProduct($identifier: ProductUniqueIdentifier) {
  product(identifier: $identifier) @context(provider: "vtex.catalog-graphql") {
    id
    name
    description
    shortDescription
    metaTagDescription
    title
    linkId
  }
}
