query GetProduct($identifier: ProductUniqueIdentifier) {
  product(identifier: $identifier) {
    id
    name
    description
    shortDescription
    metaTagDescription
    title
    linkId
    keywords
  }
}
