query getProdTransInfoReq($requestId: String!) {
  productTranslationRequestInfo(requestId: $requestId) {
    requestId
    requestedBy
    categoryId
    error
    createdAt
    locale
    completedAt
  }
}
