query translationUploadRequestInfo($requestId: String!, $bucket: String!) {
  translationUploadRequestInfo(requestId: $requestId, bucket: $bucket)
    @context(provider: "vtex.admin-catalog-translation") {
    requestId
    translatedBy
    createdAt
    estimatedTime
    error
    progress
    locale
  }
}
