mutation uploadSpecificationTranslationsImport(
  $locale: String!
  $fields: Upload!
) {
  uploadSpecificationTranslationsImport(locale: $locale, fields: $fields)
    @context(provider: "vtex.admin-catalog-translation")
}
