mutation uploadCollectionTranslations($locale: String!, $collections: Upload!) {
  uploadCollectionTranslations(locale: $locale, collections: $collections)
    @context(provider: "vtex.admin-catalog-translation")
}
