mutation uploadCollectionTranslations(
  $locale: String!
  $collections: Upload!
  $xVtexTenant: String!
) {
  uploadCollectionTranslations(
    locale: $locale
    collections: $collections
    xVtexTenant: $xVtexTenant
  ) @context(provider: "vtex.admin-catalog-translation")
}
